name: CI-MLflow-Workflow-Advance

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mlflow pandas scikit-learn docker

      - name: Run MLflow Project (Training)
        run: mlflow run Workflow-CI/MLProject --experiment-name "Workflow_CI_Experiment" --env-manager local

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-hasil-training
          path: mlruns/

      - name: Build and Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          # Login ke Docker Hub
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          
          # Build Docker Image menggunakan model hasil training
          # Pastikan nama image sesuai dengan repositori Docker Hub kamu
          mlflow models build-docker -m runs:/$(ls mlruns/0 | head -n 1)/ci_model -n $DOCKER_USER/model-hasil-training:latest
          
          # Push ke Docker Hub
          docker push $DOCKER_USER/model-hasil-training:latest