name: CI-MLflow-Workflow-Advance

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mlflow==2.11.0 pandas scikit-learn

      - name: Run MLflow Project
        run: |
          # PERBAIKAN PATH: cd ke Workflow-CI/MLProject
          cd Workflow-CI/MLProject
          mlflow run . -P alpha=0.5 -P l1_ratio=0.5 --env-manager local

      - name: Get Latest Run ID
        id: get_run_id
        run: |
          cd Workflow-CI/MLProject
          LATEST_RUN=$(ls -td mlruns/0/[0-9a-f]* | head -n 1 | xargs basename)
          echo "run_id=$LATEST_RUN" >> $GITHUB_OUTPUT
          echo "Latest Run ID: $LATEST_RUN"

      - name: Upload Model Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: Workflow-CI/MLProject/mlruns/

      - name: Commit Artifacts to Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Workflow-CI/MLProject/mlruns/
          git commit -m "Save model artifacts from CI run" || echo "No changes"
          git push

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd Workflow-CI/MLProject
          mlflow build-docker . -t ${{ secrets.DOCKER_USERNAME }}/msml-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:latest